version: '3.8'

services:
  focus-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: ["uvicorn", "server:socket_app", "--host", "0.0.0.0", "--port", "3000", "--reload"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s