name: Documentation CI/CD

on:
  push:
    branches: [main, develop]
    paths: ['docs/**', 'README.md', '.github/workflows/docs-ci.yml', 'mkdocs.yml']
  pull_request:
    branches: [main, develop]  
    paths: ['docs/**', 'README.md', '.github/workflows/docs-ci.yml', 'mkdocs.yml']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
          
      - name: Install Documentation Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          
      - name: Validate MkDocs Configuration
        run: |
          mkdocs build --strict --clean
          
      - name: Lint Markdown Files
        run: |
          npm install -g markdownlint-cli
          find docs -name "*.md" -exec markdownlint {} + || true

  build-deploy:
    name: Build and Deploy Docs
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/main'
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          
      - name: Build Documentation
        run: |
          mkdocs build --strict --clean
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'site'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4